import type { Metadata } from "next";

import "./globals.css";



import Template from "@/components/Template";

import { Open_Sans } from 'next/font/google'

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:
  Readonly<{
    children: React.ReactNode;
  }>
) {
  
  return (
    <html   className={`${openSans.variable}  font-sans`} lang="en">
      <body>
        <Template/>
        {children}
      </body>
    </html>
  );
}

